version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: postgres_rural
    ports:
      - "5432:5432"
    networks:
      - my_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
    networks:
      - my_network

  nestjs-app:
    build:
      context: .
    container_name: nestjs-app
    environment:
      DATABASE_URL: postgres://postgres:postgres123@db:5432/postgres_rural
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres123
      DB_NAME: postgres_rural
    ports:
      - "3000:3000"
    networks:
      - my_network
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local

networks:
  my_network:
    driver: bridge
